import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Build output directory
const outDir = prod ? "build" : ".";

// Ensure build directory exists in production mode
if (prod && !fs.existsSync(outDir)) {
	fs.mkdirSync(outDir, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		// "zod/v4", // 打包进 main.js 避免 Obsidian 加载失败
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(outDir, "main.js"),
	platform: "node",
});

if (prod) {
	await context.rebuild();
	
	// Copy required files to build directory
	const filesToCopy = ["manifest.json", "styles.css"];
	for (const file of filesToCopy) {
		if (fs.existsSync(file)) {
			fs.copyFileSync(file, path.join(outDir, file));
			console.log(`Copied ${file} to ${outDir}/`);
		}
	}
	
	console.log(`\n✅ Build complete! Files in ${outDir}/ directory:`);
	const files = fs.readdirSync(outDir);
	files.forEach(file => {
		const stats = fs.statSync(path.join(outDir, file));
		console.log(`  - ${file} (${(stats.size / 1024).toFixed(1)} KB)`);
	});
	
	process.exit(0);
} else {
	await context.watch();
}
